packages:
  - 'packages/**'
  - 'apps/**'
  - '!apps/nextjs/.next' # Contains a package.json
strictPeerDependencies: true
autoInstallPeers: false
allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': true
  '@swc/core': false
  esbuild: false
  sharp: false
  unrs-resolver: false
