packages:
  - 'packages/**'
  - 'apps/**'
strictPeerDependencies: true
autoInstallPeers: false
allowBuilds:
  '@nestjs/core': false
  '@swc/core': false
  esbuild: false
  sharp: false
  unrs-resolver: false
